### ISSUE TITLE
vec3.transformQuat uses slow implementation?

### ISSUE THREAD

**Issue by paulharris** [toji/gl-matrix#108]
Hi,

in vec3.js, there is a URL pointing to benchmarks.
The benchmarks indicate that the OTHER way of implementing .transformQuat() is a lot faster.

Why are we using the slow version?

cheers

**Comment by stefnotch** [comment]
Looks like the benchmark's other implementation is a broken one. The cross product wasn't implemented correctly.
Here is a fixed one: https://github.com/toji/gl-matrix/pull/231 (And also a dual quaternion implementation)
