### ISSUE TITLE
gl-matrix 2.2.1 available on NPM but 2.1.0 listed as latest version?

### ISSUE THREAD

**Issue by deathcap** [toji/gl-matrix#113]
`npm install gl-matrix@2.2.1` works as expected to get the latest version (matches git), and https://registry.npmjs.org/gl-matrix/2.2.1 exists, but https://www.npmjs.org/package/gl-matrix still shows an old version:

    Version	 2.1.0 last updated a month ago

any idea why this is? `npm install gl-matrix` also installs 2.1.0, though the latest version can be referenced in a package.json with no problem.

found this other issue, which says 2.2.1 was published about a month ago: https://github.com/toji/gl-matrix/issues/91

**Comment by toji** [comment]
npm updated to 2.3.0
