### ISSUE TITLE
Moving gl-matrix into smaller npm modules

### ISSUE THREAD

**Issue by hughsk** [toji/gl-matrix#127]
Hey @toji – awesome work with `gl-matrix`, I've been using it in all of my graphics projects since I got started with WebGL.

My only gripe, coming from the [browserify](http://browserify.org/) community, is that it's all kept in a single package: it'd be great to be able to pull in the one or two bits of it piecewise for when we're trying to trim down a script.

Would you be open to @mikolalysenko and myself forking the project to take this approach? More than happy to credit you as the author and link back to this repository from each package. Thanks!

**Comment by andrevenancio** [comment]
errr... what's wrong with
`import { vec3 } from 'gl-matrix';`

And let your webpack/rollup do the tree shaking?

**Comment by hughsk** [comment]
@andrevenancio iirc this was before tree-shaking was a thing :)
