### ISSUE TITLE
quat.fromMat3() and mat3.fromQuat() are not symmetric

### ISSUE THREAD

**Issue by torintaerum** [toji/gl-matrix#134]
Given the following code snippet I would expect 'a' and 'b' to be essentially equivalent. However 'b' appears to be the transpose of 'a'.

```
var gl_matrix = require('gl-matrix');
var mat3 = gl_matrix.mat3;
var quat = gl_matrix.quat;

var a = [
    0, -1, 0,
    1, 0, 0,
    0, 0, 1
];

var q = [];
var b = [];

quat.fromMat3(q, a);
mat3.fromQuat(b, q);
```

**Comment by devdri** [comment]
I confirm that this code fixed a similar issue for me.
Can you please check it in to the original repo so everyone can use it without patching?

**Comment by stefnotch** [comment]
This seems to be fixed.
https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/quat.js#L548

**Comment by stefnotch** [comment]
@toji Feel free to close this issue

https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/quat.js#L316
