### ISSUE TITLE
Add 1.x to 2.x migration guide and npm info? 

### ISSUE THREAD

**Issue by srcspider** [toji/gl-matrix#142]
First npm usage should be specified in the main site.

EXAMPLE

```
npm i gl-matrix --save
```

```
var glMatrix = require('gl-matrix');
var mat4 = glMatrix.mat4;
```
## 

Secondly please add some basic migration information from 1.x to 2.x, primarily for people reading code written with the old 1.x version that just wish to mentally translate it to 2.x. I've noticed it used in a lot of webgl tutorials.

EXAMPLE
- in 1.x functions had an optional dest parameter at the end of the function; in 2.x this has been moved to the front of all functions and is mandatory
- some functions will not produce the same results given the same parameters (eg. mat4.perspective)

Some example of migrating code,

What in 1.x looks like,
`mat4.translate(mvMatrix, [-1.5, 0.0, -7.0]);`
becomes in 2.x
`mat4.translate(mvMatrix, mvMatrix, [-1.5, 0.0, -7.0]);`

What in 1.x looks like,
`mat4.perspective(45, gl.viewportWidth / gl.viewportHeight, 0.1, 100.0, pMatrix)`
becomes in 2.x
`mat4.perspective(pMatrix, 45, gl.viewportWidth / gl.viewportHeight, 0.1, 100.0)`

Also in the last case you'll also encounter different results depending on which you use,
- 1.x version: `[2.4142136573791504, 0, 0, 0, 0, 2.4142136573791504, 0, 0, 0, 0, -1.0020020008087158, -1, 0, 0, -0.20020020008087158, 0]`
- 2.x version: `[1.7925909757614136, 0, 0, 0, 0, 1.7925909757614136, 0, 0, 0, 0, -1.0020020008087158, -1, 0, 0, -0.20020020008087158, 0]` 

**Source Reference**

Clear Source for 1.x functions: https://github.com/toji/gl-matrix/blob/v1.3.7/gl-matrix.js
Clear Source for 2.x functions: https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/mat4.js

_With the exception of "dest" in 1.x becoming "out" in 2.x function parameter names are generally identical._

**Comment by jasxir** [comment]
Much appreciated, the examples you presented helped me run an old demo.

**Comment by stefnotch** [comment]
@srcspider @jasxir Is this issue still relevant?

**Comment by stefnotch** [comment]
As this issue has been opened in 2014 and is about gl-matrix version 1, I'd say I can safely close it.
