### ISSUE TITLE
Gemfile missing rspec

### ISSUE THREAD

**Issue by amullins83** [toji/gl-matrix#147]
I know literally everyone with a Ruby install has RSpec installed, but since it _is_ required to run `rake build`, should it not be listed in the Gemfile? I wouldn't have run into this, but I just reinstalled Ruby on a Windows box (bad idea, right?), and was surprised to find I was missing a dependency after running `bundle install`. Technically, it was after running `bundle update` because the version of `ffi` pointed to by the included `Gemfile.lock` isn't compatible with Windows.

**Comment by toji** [comment]
Ruby dependency has been removed.
