### ISSUE TITLE
mat4.lookAt optimization

### ISSUE THREAD

**Issue by Cleric-K** [toji/gl-matrix#152]
In mat4.lookAt function:
Is the normalization of the Y(y0,y1,y2) vector really necessary?

First we get Z (EYE - CENTER) and normalize it.
Then we compute X (UP cross Z) and normalize it too.
Now it is guaranteed that Y (Z cross X) is also normalized, since Z and X are orthogonal unit vectors, so we can safely skip normalization.

**Comment by nickdesaulniers** [comment]
On paper, yes.  On IEEE754, no.
