### ISSUE TITLE
2.3.0 (?) or 2.2.3 release

### ISSUE THREAD

**Issue by jenanwise** [toji/gl-matrix#156]
I know there few issues already (#144 and #128) about releases. This issue is just an explicit request for a fresh release as of 2015-04-15, as there have been a number of changes to master since the referenced versions in those files. As of that date and up through commit 983967a:

* `2.2.1` is the latest tagged release
* `2.1.0` is latest in github releases and npm
* The files in `dist/` are labeled as `2.2.2` (unminified) and `2.2.1` (minified).
* `VERSION` lists `2.1.0`.
* `bower.json` lists `2.2.0`.
* `package.json` lists `2.3.0`.

PR #155 fixes the version inconsistencies (not including dist/) and #154 fixes the build scripts, which together should allow for a latest release.

Thanks for the great lib!

**Comment by wwwtyro** [comment]
+1

**Comment by DiThi** [comment]
I need npm to have at least version 2.2 as well.

**Comment by toji** [comment]
npm now updated to version 2.3.0. Sorry about the long (LONG) delay. Had to find the time to revamp the build system.

**Comment by DiThi** [comment]
Note that I used 2.2 for a long time, then tried to use 2.3 but there was bugs (or 2.2 had bugs my code relied in). I'll find out another day what are the differences.
