### ISSUE TITLE
.add for matrices?

### ISSUE THREAD

**Issue by mwcz** [toji/gl-matrix#158]
I'm 99% sure I'm missing something completely obvious, but the other day I tried to add two mat3's, and was surprised to find no add function.  Can someone enlighten me?

**Comment by MasterJames** [comment]
There is add and subtract in vec4 and a reference in quad to use that add.
it maybe avoided for optimization (not used much) and easy to "add" when needed. 
This remains a good question but I hope this helps to get a resolution.

**Comment by thomcc** [comment]
This was fixed by #193 and should be closed.

**Comment by mwcz** [comment]
Nice, thanks @thomcc!
