### ISSUE TITLE
Where's the "toInverseMat3" in 2.x？

### ISSUE THREAD

**Issue by CSGrandeur** [toji/gl-matrix#159]

**Comment by MasterJames** [comment]
How about mat3.fromMat4 and then invert?
https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/mat3.js

**Comment by CSGrandeur** [comment]
Thanks~It works

**Comment by stefnotch** [comment]
This function seems to do what you want: glmatrix.net/docs/module-mat3.html#.invert

**Comment by ryancat** [comment]
Should be able to use `mat3.normalFromMat4` now.
