### ISSUE TITLE
Make it possible to run gl-matrix  in non browser environment (e.g: d8, node)

### ISSUE THREAD

**Issue by nedn** [toji/gl-matrix#161]
It would be great to make it possible to run gl-matrix  in non browser environment (e.g: d8, node).

(Context: https://docs.google.com/document/d/1-y-so2o0s9o93gERJ1To-1zywTf8aJ7yzCgbeSYgwvQ)

**Comment by toji** [comment]
Just published a new version to npm and this repo. Give it a try and let me know if you run into issues!

**Comment by antoinejaussoin** [comment]
I did run into a problem with the new 2.3.0 compared to 2.1.0 using Browserify.
The 2.1.0 worked all right, but the 2.3.0 returns an empty object when requiring gl-matrix. I'll open an issue.
