### ISSUE TITLE
2.3.0 breaks compatibility with Browserify

### ISSUE THREAD

**Issue by antoinejaussoin** [toji/gl-matrix#162]
Between 2.1.0 and 2.3.0, the Browserify compatibility broke.

Require-ing gl-matrix returns an empty object.

I rolled back to 2.1.0 and it's working fine, which indeed mean the problem is in that new version.

Thanks!

**Comment by Fyrd** [comment]
Ran into the same issue. Looks like `dist/gl-matrix.js` is no longer generated, only `dist/gl-matrix-min.js`.

**Comment by winduptoy** [comment]
Same. Causing issues getting https://github.com/stackgl/webgl-workshop to run.
