### ISSUE TITLE
Please don’t minify npm module

### ISSUE THREAD

**Issue by Swatinem** [toji/gl-matrix#165]
Having npm distribute a pre-minified version really messes up my debugging ability. I would like all my code and dependencies to be full sources in development.
If I want minification, I will do it myself.

**Comment by hughsk** [comment]
@Swatinem the npm module points to `./src/gl-matrix.js` when being run through node or browserify. Are you still having problems?

**Comment by Swatinem** [comment]
Ok, I have to try again, maybe I messed something up myself

**Comment by toji** [comment]
@hughsk is correct, using from within npm should point directly to the uncompiled source. Even so, I've added an unminified build back into dist/ because the same debugging argument applies to browser use as well.
