### ISSUE TITLE
SIMD.js optimizations

### ISSUE THREAD

**Issue by nickdesaulniers** [toji/gl-matrix#171]
Looks like we'll have SIMD in es7.  Let's look at how we can take advantage if SIMD is available at runtime.

**Comment by nickdesaulniers** [comment]
Currently, I'm working on a PR based on: https://gist.github.com/nickdesaulniers/7fe015f310f85b282b5e and feedback from a discussion over email.

**Comment by nickdesaulniers** [comment]
see #172

**Comment by acterhd** [comment]
Suggestion. 
https://gist.github.com/acterhd/bbd8668b8717f7623140

**Comment by giordi91** [comment]
mmmm is it possible to emulate a "static" switch in JS? In python is possible to do stuff like this:
class T(object):
    def a(self):
        print "A"
    def b(self):
        print "B"        

    if (True):
        my_func = a
    else:

        my_func = b
        
t = T()
t.my_func()

Where basically that logic in the class body is evaluated only when python reads the file and builds the blueprint of the class in memory, when we make then an instance, the constructor only is called and the configuration logic is not used anymore. If this is applicable somehow in JS it will make the configuration of the class (aka SIMD or not SIMD) a one time run thing rather then a switch per function call. Sorry if my example is in python but I come mainly from c++ and py background, just learning JS for using webgl.

**Comment by acterhd** [comment]
Look my fork https://github.com/acterhd/gl-matrix
I'm present mat4.multiply function.

**Comment by giordi91** [comment]
@acterhd . looks good but what I would like to avoid is the branch in the code, branch is quite slow and might stall the processor pipeline, hopefully the branch prediction would mitigate the problem but still is a performance hit since we are branching per function call.  my python example will evaluate the configuration logic only once and the each instance of the created class will be configured properly and each function call wont need the if statement for SIMD support. BUT i am not sure that kind of pattern can be easily implemented in JS. I am going to do some research about it.

**Comment by acterhd** [comment]
Pull request https://github.com/toji/gl-matrix/pull/174

**Comment by toji** [comment]
You can avoid the runtime switch by effectively assigning a function pointer to the desired method during the scripts load. @acterhd's patch does this, as does @nickdesaulniers, just in different forms. 

The quick example is:
```
function a() { /* ... */ }
function b() { /* ... */ }
var c = METHOD_A_IS_FASTER ? a : b;
```
or
```
function c = (
  if (METHOD_A_IS_FASTER) {
    return function a() { /* ... */ }
  } else {
    return function b() { /* ... */ }
  }
)();
```
The only real functional difference is that in the first method you can call `a()` or `b()` directly if desired. Both avoid repeated runtime evaluation of the if statement.

@acterhd: Unfortunately I'm pretty busy with work and family matters right now, so it's going to take me a bit to look through your patches. Rest assured that I will get to it, though!

**Comment by acterhd** [comment]
This not all. Need FMA support and these functions will realy fast!

**Comment by nickdesaulniers** [comment]
No FMA, yet https://github.com/tc39/ecmascript_simd/issues/241#issuecomment-128082960

**Comment by acterhd** [comment]
I'm closed project. Some people already wrote some mat4 functions. See forks. 
I will working on vec4 SIMD adaptation.

**Comment by jeromew** [comment]
Does this thread and SIMD support in glMatrix still make sense now that chromium decided to remove SIMD.js from their code base ? https://news.ycombinator.com/item?id=14479166

I am trying to understand the state of things regarding math operations in javascript and the recent deprecation of SIMD.js by the chromium team does not make things clear to me as to where this is going.

**Comment by toji** [comment]
I've stripped out the SIMD code from the top of tree, given the conversation that @jeromew linked. If anyone still needs access to the SIMD code that was written you can now find it in the `simd-deprecated` branch.

Thanks to everyone who contributed SIMD code! I find it kind of a shame that it never worked out, but that's the way of the web I suppose.
