### ISSUE TITLE
DRY up SIMD/SISD split tests

### ISSUE THREAD

**Issue by nickdesaulniers** [toji/gl-matrix#175]
follow up to #172 using the pattern @toji describes here: https://github.com/toji/gl-matrix/pull/172#issuecomment-128459218

**Comment by acterhd** [comment]
Please do not write too many themes.

**Comment by nickdesaulniers** [comment]
one issue with that pattern is that I believe node caches calls to `require`.  Since we detect `SIMD_ENABLED`, once and not every time, I don't think we can require mat4 twice and have mat4.multiply refer to two different functions.

We could explicitly test `mat4[glMatrix.ENABLE_SIMD ? 'SIMD' : 'SISD'].multiply` though, and the existence of `mat4.multiply` and `mat4.mul` aliases.

**Comment by toji** [comment]
Ha! I was actually thinking about this last night and came to the same conclusion. So maybe something more like this?

```
var mat4 = require("../../src/gl-matrix/mat4.js");

function mat4Tests(useSIMD) {
  var testMat4 = useSIMD ? mat4.SIMD : mat4.SISD;

  return function() {
    // Test functions which have SIMD paths
    describe("create", function() { 
      beforeEach(function() { result = testMat4.create(); });
      it("should return a 16 element array initialized to a 4x4 identity matrix", function() { expect(result).toBeEqualish(identity); });
    });
    
    // Test functions that don't yet have a SIMD path
    if (!useSIMD) {
      /* Just use mat4 here like usual while we convert everything */
    }
  };
}

describe("mat4 (SISD)",  mat4Tests(false));
describe("mat4 (SIMD)",  mat4Tests(true));
```

**Comment by nickdesaulniers** [comment]
Another thing that must be reconciled is that the tests actually hit the breaking change (passing vanilla array literals).  Both `matA`, `matB`, and `out` are vanilla array literals, not Float32Arrays, so for the multiply we would have to wrap them in Float32Arrays or not based on `useSIMD`.

Can we instead *exclusively* use Float32Arrays in the tests?  In another thread, someone pointed to an ArrayBuffer polyfill, but if I fire up node 0.12.0's REPL, Float32Array is available.

**Comment by toji** [comment]
I'm totally fine using Float32Arrays everywhere rather than the array literals. (That's where we want things to go with the SIMD path anyway, right?)

**Comment by nickdesaulniers** [comment]
Hmm, @pjcozzi raises a [valid point](https://twitter.com/pjcozzi/status/629437184588824576) on Twitter. Our SIMD implementation is hard coded to use single precision where as he'd like to have support for double precision.

My use case is for optimizing anything I plan on passing to `glUniform`, `glVertexAttrib`, `glVertexAttribPointer`, and friends. I'm curious to understand his use case more? (Would guess generic matrix multiplication on double precision?)

**Comment by nickdesaulniers** [comment]
Actually, [nevermind](https://twitter.com/LostOracle/status/629702104794312704).

> That's where we want things to go with the SIMD path anyway, right?

Things could get messy, since SIMD defines a bunch of vector types.  Going off of what's available in FF Nightly (rather than the spec):
* `Float32x4`
* `Float64x2`
* `Int16x8`
* `Int32x4`
* `Int8x16`

And then booleans, which also now have length combinations from the latest spec change...

I think we should simply provide single precision implementations, since that's what WebGL wants, and if others want specialized implementations that do 4x4 matrix multiply with any other SIMD vector type, they can use the single precision as a reference example and swap it out or send PRs.

**Comment by toji** [comment]
I think the vast majority of glMatrix use is aimed at single-precision and WebGL interaction, so I'm not overly concerned about having SIMD code paths for every variant. I'm concerned that kind of code bloat would make the library less attractive in order to support a edge-case scenario.

I'm doing some code to improve the tests right now, should have it pushed later today.
