### ISSUE TITLE
optimized SIMD mat4 mul

### ISSUE THREAD

**Issue by nickdesaulniers** [toji/gl-matrix#176]
Follow up to #172 https://github.com/toji/gl-matrix/pull/172#issuecomment-128452413
https://github.com/juj/MathGeoLib/blob/master/src/Math/float4x4_sse.h#L306-L312

**Comment by nickdesaulniers** [comment]
it would be nice to have @sajjadt 's profiling harness to show measurements.

**Comment by nickdesaulniers** [comment]
Also, @sajjadt has a fork with a bunch of nicer implementations: https://github.com/sajjadt/gl-matrix/blob/master/src/gl-matrix/mat4.js#L1324

**Comment by nickdesaulniers** [comment]
addressed in #180 , but let's not close this until @juj's [comment](https://github.com/toji/gl-matrix/pull/180/files#r36664382) is addressed.

**Comment by mreinstein** [comment]
@toji this can probably be closed since SIMD is gone
