### ISSUE TITLE
Add/Mul constants

### ISSUE THREAD

**Issue by jdavidberger** [toji/gl-matrix#184]
I've noticed, somewhat surprisingly, there aren't functions to multiply / add scalars with vectors or matrices. This is somewhat common set of operations; any reason for this? Would a pull request for this addition be merged in?

**Comment by stefnotch** [comment]
@jdavidberger Has this issue been addressed by the PR?

**Comment by stefnotch** [comment]
I'll assume that it has been addressed and will close this issue.
