### ISSUE TITLE
Perspective giving odd results

### ISSUE THREAD

**Issue by WoodMath** [toji/gl-matrix#187]
I'm not certain if this is a bug or just my lack of understanding of the math behind the perspective matrix, but I've tried the following variations on some fixed data

```javascript
pMatrix = mat4.perspective(pMatrix, 20, gl.viewportWidth / gl.viewportHeight, -5.0, 5.0);
pMatrix = mat4.perspective(pMatrix, 25, gl.viewportWidth / gl.viewportHeight, -5.0, 5.0);
pMatrix = mat4.perspective(pMatrix, 30, gl.viewportWidth / gl.viewportHeight, -5.0, 5.0);
```

and unfoxtunatley, the handedness using the **fovy = 30** seems to be the opposite handedness of **fovy = 25**

**Comment by toji** [comment]
Angles in glMatrix are given in radians, including the FOV of the perspective function. That's bound to lead to some weirdness with the numbers you're providing:

25 Rad == 1432 Deg
30 Rad == 1719 Deg

Instead try 0.43 for 20 Deg and 0.52 for 30 Deg. (Rad = Deg * (3.14159/180.0))

**Comment by WoodMath** [comment]
K. for some reason I was going off of the Math.tan being in degrees.

**Comment by toji** [comment]
No problem! (FYI: All trig functions is Javascript use radians as well. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/tan)
