### ISSUE TITLE
just thanks

### ISSUE THREAD

**Issue by Jacq** [toji/gl-matrix#189]
Hi,
I don't know if this is the appropriate channel, but as I couldn't find any forum or similar hub tie to this project, thanks to the gl-matrix team and collaborators for the implementation of this library. 
I have borrowed the Vec2 implementation, added a few functions and embedded it in a web crowd simulator that I have been building during the past months.
Thanks,
Jacq

**Comment by toji** [comment]
My pleasure! Glad you've found it useful!
