### ISSUE TITLE
notation aij in the code

### ISSUE THREAD

**Issue by Arnache** [toji/gl-matrix#213]
This is not a bug but a matter of notations.

I've had a look at the code an noticed for mat4 that a13 refers to the element 7, ie the 4th entry of the 2nd vector. In the world I come from vectors are laid out vertically, so this would be denoted a42 in the line-column aij notation convention (4th line, 2nd column). Accounting for the usual -1 index shift this would be a31. I think OpenGL's implicit or explicit assumption is that vectors are columns. In the code, one seems to be using either the column-line aji notation convention _xor_ the convention that vectors are laid out horizontally (rows).

With this convention one ends up with weird looking code as in mat3.multiply(out,a,b):
out[0] = b00 \* a00 + b01 \* a10 + b02 \* a20;
instead of (the standard?)
out[0] = a00 \* b00 + a01 \* b10 + a02 \* b20;

I suggest permuting all i<->j in aij in the whole code.

**Comment by httpdigest** [comment]
In every function that declares local variables like `aNM`, the first index N always means the N'th column of the matrix and the second index 'M' always means the M'th row of the matrix. This is consistent everywhere. With that in mind, the current implementation of every matrix multiplication function does `a * b`. 

You propose to change that to:
> out[0] = a00 * b00 + a01 * b10 + a02 * b20;

With that change this would either alter the semantics of the method to mean: `b * a`, or swap the meaning of the indices 'N' and 'M' in `aNM`.

**Comment by Arnache** [comment]
Yes, we agree. What I propose is the second : swap aNM and aMN (consistently everywhere).
Just because I am used to aij meaning i-th line and j-th column... I know this is not a strong case.
