### ISSUE TITLE
Update glMatrix comments to support JSDoc 3

### ISSUE THREAD

**Issue by flcoder** [toji/gl-matrix#214]
jsdoc-template/publish.js can be updated to export the publish function.

**Comment by flcoder** [comment]
Actually, I can't even generate docs with whatever the newest jsdoc version is.  I get tons of errors.  Do I need to downgrade jsdoc to v2 instead of the current v3?

**Comment by flcoder** [comment]
Having discovered the link at the bottom left of http://glmatrix.net/docs/2.2.0/ which profoundly states the docs were generated with JsDoc Toolkit 2.4.0, I can now see the source of my complications.  I suppose this issue can be disposed of now, though it may be of some help to other jarheads out there like me :P

**Comment by toji** [comment]
I think this issue still has merit, but should probably be restated as "Update glMatrix comments to support JSDoc 3." Reopening for that reason.

**Comment by toji** [comment]
I've made JSDoc 3 part of the build process now. In doing so I'm no longer using the old custom template, but I think that's a worthwhile tradeoff to get things running. A better template can be rebuilt over time.

**Comment by flcoder** [comment]
Sweet, I love glMatrix.  I'm living in the Philippines where internet service is THE absolute worst on the planet so being able to generate the docs locally is a big deal for me.  Otherwise, I'm flipping a coin to see if I'm going to have to wait 10 minutes for my isp to decide to finally serve me.  I think it's good to update to JSDoc 3.  I guess it's become quite popular and seems easy to use.  I got them generated with toolkit 2.4, but there seems to be some issue with functions opting to use SIMD, you might check that out.  I can always look into the code and check the comments which is great already.  But local docs is really convenient.  Thank you.
