### ISSUE TITLE
Would you please provide a gl-matrix.d.ts file because I want to use glMatrix.js in TypeScript? 

### ISSUE THREAD

**Issue by wbse** [toji/gl-matrix#216]
Hi,
Would you please provide a gl-matrix.d.ts file because I want to use glMatrix in TypeScript? 
Thank you.

**Comment by MattijsKneppers** [comment]
I just added a pull request to DefinitelyTyped that contains all 2.3.0 definitions, with a different (stronger) typing approach than the previous definitions. I hope it is more along the lines of the author's intention: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10166

**Comment by jbmcewan** [comment]
It appears that the version on the DT repository is incorrect. It does not include the module "gl-matrix" so TypeScript emits a "can't find module" error. I have corrected what I needed to to get it working. There may be other things that are omitted, but it is a start. 

[gl-matrix.d.ts.tar.gz](https://github.com/toji/gl-matrix/files/430917/gl-matrix.d.ts.tar.gz)
