### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by arunetm** [toji/gl-matrix#218]
Are there any known use cases for adding mat8 (8x8) matrices that operates on Int16Arrays and mat16 (16x16) matrices on Int8Arrays? 
SIMD.js supports these types (int8x16, int16x8, bool8x16, uint8x16 etc) and shows significant speedups for vectorized operations on them. Is there value in having them for webgl or other applications for this library?

**Comment by stefnotch** [comment]
I don't think so.
