### ISSUE TITLE
my have follow error? what?

### ISSUE THREAD

**Issue by yanite** [toji/gl-matrix#223]
common.js?cb46_:34Uncaught TypeError: Cannot use 'in' operator to search for 'SIMD' in undefined
    at Object.<anonymous> (common.js?cb46_:34)
    at **webpack_require** (bootstrap 588009c…?a0f0**_:19)
    at Object.<anonymous> (gl-matrix.js?eab8_:29)
    at **webpack_require** (bootstrap 588009c…?a0f0**_:19)
    at Object.<anonymous> (painter.js?1c3e_:4)
    at **webpack_require** (bootstrap 588009c…?a0f0**_:19)
    at Object.<anonymous> (map.js?ba0e_:12)
    at **webpack_require** (bootstrap 588009c…?a0f0**_:19)
    at Object.<anonymous> (mapbox-gl.js?5b58_:8)
    at **webpack_require** (bootstrap 588009c…?a0f0***:19)

i see this is Object {}

**Comment by stefnotch** [comment]
You might want to include some general information such as: What browser are you using? Any libraries?

**Comment by yanite** [comment]
chrome browser  https://github.com/airbnb/caravel 
it linux ubuntu is ok 
but windows fail 

Windows_NT 10.0.10586
node v6.5.0
npm  v3.10.3


package file :: 
:: ==============================================================
{
  "name": "caravel",
  "version": "0.1.0",
  "description": "Caravel is a data exploration platform designed to be visual, intuitive, and interactive.",
  "directories": {
    "doc": "docs",
    "test": "spec"
  },
  "scripts": {
    "test": "npm run lint && mocha --compilers js:babel-core/register --required spec/helpers/browser.js spec/**/*_spec.*",
    "dev": "NODE_ENV=dev webpack -d --watch --colors",
    "prod": "NODE_ENV=production webpack -p --colors --progress",
    "lint": "npm run --silent lint:js",
    "lint:js": "eslint --ignore-path=.eslintignore --ext .js,.jsx ."
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/airbnb/caravel.git"
  },
  "keywords": [
    "big",
    "data",
    "exploratory",
    "analysis",
    "react",
    "d3",
    "airbnb",
    "nerds",
    "database",
    "flask"
  ],
  "author": "Airbnb",
  "bugs": {
    "url": "https://github.com/airbnb/caravel/issues"
  },
  "homepage": "https://github.com/airbnb/caravel#readme",
  "dependencies": {
    "autobind-decorator": "^1.3.3",
    "babel-plugin-flow-comments": "^6.3.19",
    "bootstrap": "^3.3.6",
    "bootstrap-datepicker": "^1.6.0",
    "brace": "^0.7.0",
    "brfs": "^1.4.3",
    "cal-heatmap": "3.5.4",
    "classnames": "^2.2.5",
    "d3": "^3.5.14",
    "d3-cloud": "^1.2.1",
    "d3-sankey": "^0.2.1",
    "d3-tip": "^0.6.7",
    "datamaps": "^0.4.4",
    "datatables-bootstrap3-plugin": "^0.4.0",
    "datatables.net-bs": "^1.10.11",
    "eslint-plugin-jsx-a11y": "^2.2.1",
    "font-awesome": "^4.6.3",
    "gridster": "^0.5.6",
    "immutability-helper": "^2.0.0",
    "jquery": "^2.2.1",
    "jquery-ui": "1.10.5",
    "json-loader": "^0.5.4",
    "mapbox-gl": "^0.20.0",
    "mustache": "^2.2.1",
    "nvd3": "1.8.4",
    "react": "^15.3.1",
    "react-bootstrap": "^0.28.3",
    "react-bootstrap-datetimepicker": "0.0.22",
    "react-bootstrap-table": "^2.3.7",
    "react-dom": "^0.14.8",
    "react-grid-layout": "^0.12.3",
    "react-map-gl": "^1.0.0-beta-10",
    "react-resizable": "^1.3.3",
    "react-select": "^1.0.0-beta14",
    "select2": "3.5",
    "select2-bootstrap-css": "^1.4.6",
    "supercluster": "https://github.com/georgeke/supercluster/tarball/ac3492737e7ce98e07af679623aad452373bbc40",
    "topojson": "^1.6.22",
    "transform-loader": "^0.2.3",
    "viewport-mercator-project": "^2.1.0",
    "webworkify-webpack": "^1.0.6"
  },
  "devDependencies": {
    "babel": "^6.3.26",
    "babel-core": "^6.10.4",
    "babel-loader": "^6.2.5",
    "babel-preset-airbnb": "^1.1.1",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-es2015-loose": "^8.0.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-1": "^6.13.0",
    "chai": "^3.5.0",
    "css-loader": "^0.23.1",
    "enzyme": "^2.0.0",
    "eslint": "^2.13.1",
    "eslint-config-airbnb": "^9.0.1",
    "eslint-plugin-import": "^1.11.1",
    "eslint-plugin-jsx-a11y": "^2.0.1",
    "eslint-plugin-react": "^5.2.2",
    "exports-loader": "^0.6.3",
    "file-loader": "^0.8.5",
    "imports-loader": "^0.6.5",
    "jsdom": "^8.0.1",
    "json-loader": "^0.5.4",
    "less": "^2.6.1",
    "less-loader": "^2.2.2",
    "mapbox-gl": "^0.20.1",
    "mocha": "^2.4.5",
    "react-addons-test-utils": "^0.14.8",
    "react-dom": "^0.14.8",
    "style-loader": "^0.13.0",
    "transform-loader": "^0.2.3",
    "url-loader": "^0.5.7",
    "webpack": "^1.13.1",
    "webworkify-webpack": "1.0.6"
  }
}

webpackage :: --------------------------------------------------------------------------------------------

const webpack = require('webpack');
const path = require('path');

// input dir
const APP_DIR = path.resolve(__dirname, './');

// output dir
const BUILD_DIR = path.resolve(__dirname, './javascripts/dist');

const config = {
  entry: {
    'css-theme': APP_DIR + '/javascripts/css-theme.js',
    dashboard: APP_DIR + '/javascripts/dashboard/Dashboard.jsx',
    dashboard_edit: APP_DIR + '/javascripts/dashboard/Dashboard_edit.jsx',
    explore: APP_DIR + '/javascripts/explore/explore.jsx',
    welcome: APP_DIR + '/javascripts/welcome.js',
    sql: APP_DIR + '/javascripts/sql.js',
    standalone: APP_DIR + '/javascripts/standalone.js',
    common: APP_DIR + '/javascripts/common.js',
  },
  output: {
    path: BUILD_DIR,
    filename: '[name].entry.js',
  },
  resolve: {
    extensions: [
      '',
      '.js',
      '.jsx',
    ],
    alias: { webworkify: 'webworkify-webpack' },
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: APP_DIR + '/node_modules',
        loader: 'babel',
        query: {
          presets: [
            'airbnb',
            'es2015',
            'react',
          ],
        },
      },
      /* for react-map-gl overlays */
      {
        test: /\.react\.js$/,
        include: APP_DIR + '/node_modules/react-map-gl/src/overlays',
        loader: 'babel',
      },
      /* for require('*.css') */
      {
        test: /\.css$/,
        include: APP_DIR,
        loader: 'style-loader!css-loader',
      },
      /* for css linking images */
      {
        test: /\.png$/,
        loader: 'url-loader?limit=100000',
      },
      {
        test: /\.jpg$/,
        loader: 'file-loader',
      },
      {
        test: /\.gif$/,
        loader: 'file-loader',
      },
      /* for font-awesome */
      {
        test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url-loader?limit=10000&minetype=application/font-woff',
      },
      {
        test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'file-loader',
      },
      /* for require('*.less') */
      {
        test: /\.less$/,
        include: APP_DIR,
        loader: 'style!css!less',
      },
      /* for mapbox */
      {
        test: /\.json$/,
        loader: 'json-loader',
      },
      {
        test: /\.js$/,
        include: APP_DIR + '/node_modules/mapbox-gl/js/render/painter/use_program.js',
        loader: 'transform/cacheable?brfs',
      },
      {
        test: /mapbox-gl.+\.js$/,
        loader: 'transform/cacheable?brfs'
      }
    ],
    postLoaders: [{
      include: /node_modules\/mapbox-gl/,
      loader: 'transform',
      query: 'brfs',
    }],
  },  
  externals: {
    cheerio: 'window',
    'react/lib/ExecutionEnvironment': true,
    'react/lib/ReactContext': true,
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
      },
    }),
  ],
};
if (process.env.NODE_ENV === 'production') {
  config.plugins.push(new webpack.optimize.UglifyJsPlugin());
}
module.exports = config;

:: file end --------------------------------------------------------------------------------------------

**Comment by yanite** [comment]
what is SIMD ??

**Comment by stefnotch** [comment]
[SIMD](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SIMD) stands for Single Instruction/Multiple Data. 
Basically, they allow you to do a bunch of things at the same time. For example, adding a few numbers at the same time and getting a result for each addition.

Would you mind posting the relevant lines from the stack trace?

> common.js?cb46:34

^This one

**Comment by rbgo** [comment]
SIMD is a intel CPU instruction. It allows to pass two 128 bits operants worth of data to participate in one virtual ADD, SUB, MUL, DIV (and more?) CPU instruction while the return value is 128 bits too as well. That means bringing sets of 16 x 8bits or 8 x 16bits  or 4 x 32 bits or 2 x 64bits numeric data local to CPU registers, execute the math instruction to them all (one at a time though), and storing it all back to memory, all in one pass.
This saves on the usual bringing two operants local for each math instruction. This is excellent for bulk math operations like in 3D calc, compression, encoding tasks, etc.
Its great to have a Javascript bridge to these kind of features. Only then Javascript can ever rival desktop applications.

**Comment by gblair** [comment]
FWIW, I was having I think the same issue. Looks like @yanite and I are both using `mapbox-gl-js` with webpack. Once I added `exclude: /node_modules/` to the relevant webpack loader, things started working for me.
