### ISSUE TITLE
Matrix dot column vector

### ISSUE THREAD

**Issue by thundron** [toji/gl-matrix#226]
Is it possible to define a column vector?
I'm trying to translate this Python line

```python
import dot from numpy
X = [[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]]                                                                                                                                                              
y = [[-0.16595599], [0.44064899], [-0.99977125]]
z = dot(X, y);
```

using this library

EDIT - forgot another question: how can I define a 4x3 matrix?

**Comment by httpdigest** [comment]
The vectors are already column vectors. You can multiply a column vector to the right of a matrix by using `vec3.transformMat3(resultVector, vector, matrix)`.

**Comment by thundron** [comment]
Ok, thank you.
What about defining a 4x3 matrix?

**Comment by httpdigest** [comment]
I don't think glMatrix has those currently. Just use a mat4 with the last row (elements [3], [7], [11], [15]) being (0, 0, 0, 1) and transform vec4's with w=1.

**Comment by thundron** [comment]
Thank you very much
