### ISSUE TITLE
Matrix by vector multiplication?

### ISSUE THREAD

**Issue by xamgore** [toji/gl-matrix#232]
Hi! There is a [problem](http://webglfactory.blogspot.ru/2011/05/how-to-convert-world-to-screen.html), when you need to compute something like this: 

```
3Dcoord = inverse(projectionMatrix * viewMatrix) * [x, y, 0, 1];
```

But I don't find any functions like `mat4.multiplyByVec4`, that's strange, don't you think so?

**Comment by httpdigest** [comment]
[vec4.transformMat4](https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/vec4.js#L496)

**Comment by stefnotch** [comment]
If you have any issues with that in the future, remember: The methods are grouped by their **return value**.

**Comment by xamgore** [comment]
@httpdigest, thank you.

**Comment by Jim-Cen** [comment]
Yes，vec4.transformMat4 can solve my problem. But it againsts fluent style.

**Comment by xamgore** [comment]
@httpdigest maybe you should make an alias for `vec4.transformMat4` in the `mat4` module? Or write a documentation tip for newcomers?
