### ISSUE TITLE
quat.fromAxes column-major or row-major?

### ISSUE THREAD

**Issue by gameknife** [toji/gl-matrix#234]
gl-matrix is a fatanstic mathlib on js, I found a problem when I use 3 basis vector to construct a quaternion.

quat.fromAxes use the 3 basis vector to construct a **column-major mat3**, then convert this mat3 to quat.

but I notice that the mat4.lookAt use **row-major**, so when consttuct a ViewMatrix from quat, that cause some problem. 

I'm wondering the quat.fromAxes should have a chance to choose row-major or column-major when calling?

Thanks to the dev-team of gl-matrix!

**Comment by stefnotch** [comment]
Related to https://github.com/toji/gl-matrix/issues/225
