### ISSUE TITLE
Small error in the documentation

### ISSUE THREAD

**Issue by ArnaudDroxler** [toji/gl-matrix#237]
In the documentation page of the vec3, there's a small error.
It's about the fonction transformMat3 who transforms the vec3 with a mat3.
The parameter type of the matrix in the documentation are false.
It's require a mat3 and in the doc it's a mat4 

Parameters:
Name	Type	Description
out	        vec3	         the receiving vector
a	        vec3	         the vector to transform
m	        mat4         the 3x3 matrix to transform with

Thanks you

**Comment by toji** [comment]
Fixed in #249
