### ISSUE TITLE
Are these matrix operations supported?

### ISSUE THREAD

**Issue by TheInvoker** [toji/gl-matrix#238]
Hi, does your library support doing these matrix operations? Note all the dimensions will be known on runtime. The heights will be 3 dimension, but the widths can be any dimension.

![capture2](https://cloud.githubusercontent.com/assets/5560751/23268647/6776ac68-f9bc-11e6-9f00-36e81bb2a2f5.PNG)
![capture3](https://cloud.githubusercontent.com/assets/5560751/23268924/029ec4fa-f9bd-11e6-8c09-7e28620a1c74.PNG)
![capture1](https://cloud.githubusercontent.com/assets/5560751/23268649/6781e448-f9bc-11e6-81a5-32342f6847e2.PNG)

**Comment by stefnotch** [comment]
No, glmatrix was made for speed. It only supports 4*4 matrices.
