### ISSUE TITLE
Using without polluting the global namespace

### ISSUE THREAD

**Issue by computersarecool** [toji/gl-matrix#244]
At risk of repeating #112 (which was closed without a solution), in the browser, when including this, all of teh classes are added to the global (window) object.

Would you guys be willing to encapsulate this more so we do not have to use something like browserify to keep this out of the window object?

I think that adding everything to a glMatrix object (which itself if a member of the window object) would be very helpful

**Comment by toji** [comment]
#249 converts the library to use ES2015 modules. The pre-compiled scripts in the `dist/`directory will continue to place all functions in the global namespace, but libraries that want to include a more targeted set of functionality can now use the individual modules directly.
