### ISSUE TITLE
mat4.getRotation is not working when the matrix was scaled with specific vectors.

### ISSUE THREAD

**Issue by kyasbal-1994** [toji/gl-matrix#245]
I noticed `mat4.getRotation` can return distorted quaternion when I passed specific matrix to the method.
Let assume there was a matrix scaled with a vector of which element values are not same.
In that case, I guess this code would not work correctly.
```js
mat4.getRotation = function (out, mat) {
  // Algorithm taken from http://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToQuaternion/index.htm
  var trace = mat[0] + mat[5] + mat[10];
  var S = 0;

  if (trace > 0) { 
    S = Math.sqrt(trace + 1.0) * 2;
    out[3] = 0.25 * S;
    out[0] = (mat[6] - mat[9]) / S;
    out[1] = (mat[8] - mat[2]) / S; 
    out[2] = (mat[1] - mat[4]) / S; 
  } else if ((mat[0] > mat[5])&(mat[0] > mat[10])) { 
    S = Math.sqrt(1.0 + mat[0] - mat[5] - mat[10]) * 2;
    out[3] = (mat[6] - mat[9]) / S;
    out[0] = 0.25 * S;
    out[1] = (mat[1] + mat[4]) / S; 
    out[2] = (mat[8] + mat[2]) / S; 
  } else if (mat[5] > mat[10]) { 
    S = Math.sqrt(1.0 + mat[5] - mat[0] - mat[10]) * 2;
    out[3] = (mat[8] - mat[2]) / S;
    out[0] = (mat[1] + mat[4]) / S; 
    out[1] = 0.25 * S;
    out[2] = (mat[6] + mat[9]) / S; 
  } else { 
    S = Math.sqrt(1.0 + mat[10] - mat[0] - mat[5]) * 2;
    out[3] = (mat[1] - mat[4]) / S;
    out[0] = (mat[8] + mat[2]) / S;
    out[1] = (mat[6] + mat[9]) / S;
    out[2] = 0.25 * S;
  }

  return out;
};

```
The local variable `S` is for re-scaling to fetch rotation values. But this same value of S is used for all rows. That is why `getRotation` with scaled matrix is not working in every situations.

This is the easist way to fix this with re-scaling each matrix elements.

```js

mat4.getRotation = function (out, mat) {
    var m11 = mat[0],
      m12 = mat[1],
      m13 = mat[2],
      m21 = mat[4],
      m22 = mat[5],
      m23 = mat[6],
      m31 = mat[8],
      m32 = mat[9],
      m33 = mat[10];
   var s1 =1/ Math.sqrt(m11 * m11 + m12 * m12 + m13 * m13);
   var s2= 1/Math.sqrt(m21 * m21 + m22 * m22 + m23 * m23);
   var s3 = 1/Math.sqrt(m31 * m31 + m32 * m32 + m33 * m33);
  var trace = mat[0]*s1 + mat[5]*s2 + mat[10]*s3;
  var S = 0;
  if (trace > 0) { 
    S = Math.sqrt(trace + 1.0) * 2;
    out[3] = 0.25 * S;
    out[0] = (mat[6]*s3 - mat[9]*s2) / S;
    out[1] = (mat[8]*s1 - mat[2]*s3) / S; 
    out[2] = (mat[1]*s2 - mat[4]*s1) / S; 
  } else if ((mat[0]*s1 > mat[5]*s2)&(mat[0] *s1> mat[10]*s3)) { 
    S = Math.sqrt(1.0 + mat[0]*s1 - mat[5]*s2- mat[10]*s3) * 2;
    out[3] = (mat[6]*s3 - mat[9]*s2) / S;
    out[0] = 0.25 * S;
    out[1] = (mat[1]*s2 + mat[4]*s1) / S; 
    out[2] = (mat[8]*s1 + mat[2]*s3) / S; 
  } else if (mat[5]*s2 > mat[10]*s3) { 
    S = Math.sqrt(1.0 + mat[5]*s2 - mat[0]*s1 - mat[10]*s3) * 2;
    out[3] = (mat[8]*s1 - mat[2]*s3) / S;
    out[0] = (mat[1]*s2 + mat[4]*s1) / S; 
    out[1] = 0.25 * S;
    out[2] = (mat[6]*s3 + mat[9]*s2) / S; 
  } else { 
    S = Math.sqrt(1.0 + mat[10]*s3 - mat[0] *s1- mat[5]*s2) * 2;
    out[3] = (mat[1]*s2 - mat[4]*s1) / S;
    out[0] = (mat[8]*s1 + mat[2]*s3) / S;
    out[1] = (mat[6]*s3 + mat[9]*s2) / S;
    out[2] = 0.25 * S;
  }

  return out;
};
```

But this should be able to be simplified. This is just a monkey patch.
Thanks.

**Comment by stefnotch** [comment]
@kyasbal-1994 Does @alinz PR solve your issue?

**Comment by IcanDivideBy0** [comment]
@stefnotch I think the bug is still there. Using `mat4.getRotation` on scaled matrix gives me strange behaviors (distortions) that are fixed by using the @kyasbal-1994 version.

Having this merge whould have saved me hours of headache!

Do you think this version can me merged as is or do you prefer to simplify it first ?

**Comment by stefnotch** [comment]
@IcanDivideBy0 I can merge this. Would you or @kyasbal-1994 mind cleaning up the code a bit and opening a PR?

**Comment by IcanDivideBy0** [comment]
Sure, I'll try to send something today. I can clean it up but for simplification, I don't really understand what's going on there... just tried it out of despair and fixed all my issues :D

**Comment by stefnotch** [comment]
@IcanDivideBy0 Regarding the simplifications and cleaning up, it would be great if you could
- Replace `var` with `let`
- Replace things like `mat[6]` with their cached values `m23`
- Replace `&` with `&&`
- Optionally, you can cache things that get calculated multiple times such as `mat[0]*s1`
- Format the code

I don't think the mathematics part can easily be simplified, so don't worry about it.

**Comment by IcanDivideBy0** [comment]
this implementation is breaking some tests :/

```
  1) quat2
       from/toMat4
         quat to matrix and back
           should be equal to the starting dual quat:

      AssertionError [ERR_ASSERTION]: expected 1 to be equalish to 0.05601895600557327
      + expected - actual

      -1
      +0.05601895600557327
      
  2) quat2
       from/toMat4
         quat to matrix and back
           should be equal to the starting dual quat:

      AssertionError [ERR_ASSERTION]: expected 2 to be equalish to 0.35028064250946045
      + expected - actual

      -2
      +0.35028064250946045
```

**Comment by IcanDivideBy0** [comment]
I don't think we can get both the quat2 in and out equality and the scale corrected. As I suggest in the PR, let me know what you think about adding another function.

**Comment by IcanDivideBy0** [comment]
Or maybe an even simpler solution which is adding a comment to the doc:

> If `mat` is scaled, you probably want to unscale it first like so:
```
const scale = mat4.getScaling([], mat);
const invScale = vec3.inverse([], scale);
const matInvScaling = mat4.fromScaling([], invScale);
const unscaledOut = mat4.mul([], matInvScaling, mat);
mat4.getRotation(out, unscaledOut);
```

**Comment by stefnotch** [comment]
@IcanDivideBy0
It's possible that the quat2 tests aren't 100% correct. (I assumed that the rest of the library is bug free when I created those tests.)
