### ISSUE TITLE
& should be &&

### ISSUE THREAD

**Issue by hsaransa** [toji/gl-matrix#255]
https://github.com/toji/gl-matrix/blob/a8540ceb6604acf13848d8e796222b02851d8431/src/gl-matrix/mat4.js#L1014

**Comment by YoYoYonnY** [comment]
Why? I'm pretty sure `&` is faster and doesn't affecting the result.

**Comment by rbgo** [comment]
With some operands the result may indeed be the same:
```
(0 & 0) == false;
(0 && 0) == false;
```
But may differ too:
```
(0x01 & 0x80) == false; //bitwise AND; reading if most signficant bit of the first byte evaluates to true.
(0x01 && 0x80) == true;//logical AND; if both operands evaluate to true.
```

**Comment by hsaransa** [comment]
gl-matrix doesn't compile with typescript because of that. I'm pretty sure that all JITs produce the same native code.

**Comment by YoYoYonnY** [comment]
`assert([[true, true], [true, false], [false, true], [false, false]].every(x => Boolean(x[0] & x[1]) == Boolean(x[0] && x[1])));`

`<` returns a boolean result, so `&` and `&&` always return the same result.

**Comment by YoYoYonnY** [comment]
@hsaransa I'd think TypeScript fails to compile because TypeScript requires `&` to take arguments of type `number`. JavaScript/ECMAScript doesn't.

**Comment by hsaransa** [comment]
I don't actually mind if this is fixed or not, I have my local fix for typescript. There are plenty of other shitness that actually should be fixed, but once you read the source code, this is pretty ok and easily avoided. But this kind of library should not have random epsilons for equality for example. The epsilon is always wrong for any practical application. Keep it simple, don't put in shit that lures users into bad habits. There is a reason that GL/GLU/GLUT didn't have epsilons.

**Comment by stefnotch** [comment]
Looks like this issue has been fixed: https://github.com/toji/gl-matrix/blob/a24a7113c856696de1d7a993ffaf9021e86cecd1/src/gl-matrix/mat4.js#L1014
