### ISSUE TITLE
Invocation of not defined function in lookAt

### ISSUE THREAD

**Issue by artvinn** [toji/gl-matrix#256]
Hey guys, can someone explain me how this line is supposed to work, as it throws me an error? There is no any mat4 object you can refer to. I suppose it should be just `return identity(out)` ?

https://github.com/toji/gl-matrix/blob/a8540ceb6604acf13848d8e796222b02851d8431/src/gl-matrix/mat4.js#L1370

**Comment by artvinn** [comment]
https://github.com/toji/gl-matrix/pull/257

**Comment by zero298** [comment]
I think you're right.  It was probably a miss during 1965b52a3c3f5c05b846245efc9bcbe510924a74 when the `mat4` class was removed.

**Comment by stefnotch** [comment]
@artvinn You can close this issue now.
