### ISSUE TITLE
Cannot import gl-matrix.js

### ISSUE THREAD

**Issue by sannyi** [toji/gl-matrix#266]
I am having trouble to import the gl-matrix-js library. 
My html head is 
`<head>
        <meta charset="utf-8" />
        <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
        <script  src="./dist/gl-matrix.js type="text/javascript""></script>
        </head>`
When I type "mat4." it doesn't show up the create function or anything like that. What I am doing wrong?

**Comment by stefnotch** [comment]
One of your quotation marks is in the wrong place. (Decent syntax highlighting makes catching those errors dead easy.)
```
<script src="./dist/gl-matrix.js type="text/javascript""></script>
                                ^Put " here            ^Nope
```

**Comment by sannyi** [comment]
Thanks for the error correction. Enabled syntax highlighting and now it works. 🥇

**Comment by sannyi** [comment]
` <script  src="./dist/gl-matrix.js" type="text/javascript"></script>` is the new code, but mat4.create, still doesn't show up. Should VS2017's Intellisense display the  "create" (an all the other method or do I have to write them down first time calling them?

**Comment by stefnotch** [comment]
Do they work? If yes, it's IntelliSense's fault.

Also, what's your file structure? (Where is the .html file and where did you put your gl-matrix.js file?)

**Comment by sannyi** [comment]
My html file is in the project root folder, the gl is directly in dist folder.

**Comment by stefnotch** [comment]
Try out something like:
```
<script>
if(mat4) document.body.innerHTML = "IT WORKS";
</script>
```

If you can see the text `IT WORKS`, then it probably works.

**Comment by sannyi** [comment]
It looks like VS's intellisense is ass, since I added the if statement to the keypress event and the if statement executes... So I have to find a way to this up to display all in VS's 2017 Intellisense. Thanks.

**Comment by stefnotch** [comment]
Here is a hack that might work:
```
function require() {
  return null;
}
var glMatrix, quat, mat4, vec3; //etc
if (false) {
  glMatrix = require("./gl-matrix-min.js");
  quat = require("./dist/quat.js");
  mat4 = require("./dist/mat4.js");
  vec3 = require("./dist/vec3.js");
}
```
another one that might just work if IntelliSense is dumb enough:
```
if(false) {
  import quat from "./dist/quat.js"

}
```
Note: You will have to download all of those files: https://github.com/toji/gl-matrix/tree/master/src/gl-matrix

**Comment by sannyi** [comment]
Are ./dist/quat.js, ./dist/mat4.js, ./dist/vec3.js separate files? If yes, then there is only gl-matrix.js and it's minified copy.

**Comment by stefnotch** [comment]
Yes, all of them are separate files: https://github.com/toji/gl-matrix/tree/master/src/gl-matrix
If IntelliSense is simplistic enough, it might be possible to trick it into believing that those files are part of the project and that it should provide some autocomplete stuff for them.

**Comment by sannyi** [comment]
Seem's it's something wrong with VS 2017. I included https://cdnjs.cloudflare.com/ajax/libs/gl-matrix/2.4.0/gl-matrix.js and still nothing with Intellisense.

**Comment by sannyi** [comment]
Currently I am using Notepad++ and I guess I'd have send a suggestion to VS 2017 Insider Program. With notepad it just work fine. Thank you for the help.
