### ISSUE TITLE
dist: mat4.identity referenced when mat4 not reachable

### ISSUE THREAD

**Issue by sebastien** [toji/gl-matrix#269]
In the [dist built](https://github.com/toji/gl-matrix/blob/master/dist/gl-matrix.js#L5236) at *line 5236*, we have

```
  return mat4.identity(out);
```

however, `mat4` is not defined at this level, resulting in a *runtime error*. This should be `return identity(out)`. The [original source code is right](https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/mat4.js#L1370), though:

```
 return identity(out);
```

the issue probably lies in the tools used to compile the distribution package.

**Comment by andrevenancio** [comment]
We'll be able to close a few issues and PR's if we bump the version to `2.4.1` and run `npm publish`.
Otherwise import it via github instead. not pretty but works if you stuck

**Comment by andrevenancio** [comment]
zZzzZZzz :(

**Comment by sebastien** [comment]
I've patched my local version, so it's fine for me -- I got the version from unpkg <https://unpkg.com/gl-matrix@2.4.0/dist/gl-matrix.js> BTW

**Comment by andrevenancio** [comment]
I'm also running a version locally with the fix hardcoded.. solves my problem for now, but anyone pulling my repo and doing `npm i` is doomed to fail :) I would leave it for a bit of pressure :)

**Comment by stefnotch** [comment]
@sebastien @andrevenancio This issue should be resolved 😄

**Comment by sebastien** [comment]
Confirming it's fixed in https://unpkg.com/gl-matrix@2.4.1/dist/gl-matrix.js. Thanks!

**Comment by andrevenancio** [comment]
wow just took half a year! (sarcasm emoji here).

**Comment by stefnotch** [comment]
@andrevenancio 🤣 Yeah, I know. It's because toji is pretty busy with other stuff and I didn't become maintainer until recently.
