### ISSUE TITLE
Can't build gl-matrix with Webpack throught UglifyJS

### ISSUE THREAD

**Issue by MathieuDebit** [toji/gl-matrix#270]
I have an issue when trying to bundle a basic app with `gl-matrix` (installed from npm) using Webpack and the UglifyJSPlugin.
The error occurs only when this plugin is used for the bundle:

```
ERROR in bundle.js from UglifyJs
Unexpected token: name (ARRAY_TYPE) [bundle.js:104,4]
```

I also have this issue when using https://github.com/vuejs-templates/webpack:
```
ERROR in static/js/vendor.13ee0770ae53389217e3.js from UglifyJs
Unexpected token: name (out) [./node_modules/gl-matrix/src/gl-matrix/vec2.js:34,0][static/js/vendor.13ee0770ae53389217e3.js:154,6]
```

Here is a repo to reproduce the issue: https://github.com/MathieuDebit/gl-matrix-webpack.

Thanks!

**Comment by agenthunt** [comment]
It is an issue with default webpack uglify plugin https://github.com/webpack/webpack/issues/2972
Try this workaround.

```
const UglifyJsPlugin = require("uglifyjs-webpack-plugin");

...
      new UglifyJsPlugin({
        sourceMap: true,
        compress: {
          screw_ie8: true,
          warnings: false
        },
        output: { comments: false }
      })
    ),
```

**Comment by MathieuDebit** [comment]
Thank you @agenthunt! I updated my test repo but unfortunately I still have the same error...

**Comment by agenthunt** [comment]
Seems like it needed babel and babel preset es2015 as well. Sent a PR to your test repo.

**Comment by MathieuDebit** [comment]
Thanks a lot for your help 👌

**Comment by netdeamon** [comment]
@agenthunt fix solved the issue.
