### ISSUE TITLE
is repo being maintained ?

### ISSUE THREAD

**Issue by andrevenancio** [toji/gl-matrix#272]
I've been following a couple of `Issues` and `Pull requests` that interest me. And its been a while since I see any activity in the repo, from @toji despite the `tags`. I for example, have a 2 week old PR with no comment from any users / admins.

I'm making myself available to help in any way possible. either to test stuff, or to help setting up priorities, but we're getting to a point where a lot of things are pilling up.

I'm already "living" from a fork from this repo with some change to fix a couple of issues, but I don't think this is the right approach.

Again, happy to help where I can.

**Comment by stefnotch** [comment]
It might be a good idea to create and maintain your own fork, since @toji seems to be quite busy most of the time. Also, this repository has a huge backlog of issues which were never closed, even though they should be.

@toji What do you think?

**Comment by andrevenancio** [comment]
I really think that's not the best way... People don't need to be looking for a branch from this repo and see which one is better maintained. I understand the work load might be a lot, but its up to @toji and @sinisterchipmunk to either allow collaborators who can spend more time here and close issues, review PRs merge changes, or just make a yearly review or something 😃

**Comment by andrevenancio** [comment]
Yeah I know, I remember being on a chat with you on another issue 😛 There's definitely people into gl-matrix 😛

**Comment by andrevenancio** [comment]
Now I've noticed that someone added a PR that does the same as an old PR I've submitted. 
Which is exactly the point of this issue. We need some love on this repo...
