### ISSUE TITLE
Do you have old-version?

### ISSUE THREAD

**Issue by hyunsooda** [toji/gl-matrix#273]
Hello, I'm korea university student.
Actually, I bought a book related to webgl.
However this book use very old version as well as min-version, so I can't find out original old version.
By any chance, would you give the original old version(1.2.4v (not minified version) ? if you have.

**Comment by stefnotch** [comment]
Well, you can find a bunch of older versions here: https://github.com/toji/gl-matrix/releases

Though, it shouldn't be too hard to just use the newest version.

**Comment by hyunsooda** [comment]
Oh yes, I usally use newest version.
However I decided to use old version for my convenience when I execute book example because my book use old version.

ah, I just found a site that user allow to convert from min-ver to beautify-ver.
anyway, thanks for responding! have a nice day:)

**Comment by stefnotch** [comment]
https://github.com/toji/gl-matrix/blob/e8744aebda43a297c7a9f45675b8a9d04fece6d4/gl-matrix.js

Here you go: Version 1.2.4 of glmatrix! :)


Also, feel free to close this issue if it is resolved.
