### ISSUE TITLE
submodules are imported from src and not dist, creating issues in older browsers

### ISSUE THREAD

**Issue by hartbeatnt** [toji/gl-matrix#277]
the line following line `const {mat3} = require('gl-matrix')`

causes webpack (v.2.2.0-rc.3) to load the mat3 file from src, and not dist, into the bundle. This leaves in all the `let` and `const` declarations, which break in older broswers.

Changing the import to `const {mat3} = require('gl-matrix/dist/gl-matrix-min.js')` solves the issue, but is an unideal workaround

**Comment by zero298** [comment]
I would kind of expect this behavior.  However, if you are targetting ES5, wouldn't webpack be transpiling to ES5 already?  Are you using something like https://github.com/babel/babel-loader?

**Comment by hartbeatnt** [comment]
webpack is typically set up to not transpile anything from the node_modules directory, as to do so would drastically increase the bundling time. It is expected that when downloading a module from npm, the dist file would already be transpiled to es5

**Comment by TimvanScherpenzeel** [comment]
I'm currently using the following configuration to include gl-matrix when transpiling my own library.

<img width="469" alt="config" src="https://user-images.githubusercontent.com/11870513/35768736-26cf3dd8-0901-11e8-8551-068baacba999.png">

**Comment by jameswilddev** [comment]
Could this be causing:
```
\node_modules\gl-matrix\src\gl-matrix\vec3.js:21
import * as glMatrix from "./common";
^^^^^^

SyntaxError: Unexpected token import
```

(using babel-register to use gl-matrix from inside a Node.JS app)

**Comment by stefnotch** [comment]
Is this still an issue?

**Comment by jameswilddev** [comment]
Yeah I was using babel-register which can sort of do the same thing (babel-register is more suited to apps which run directly under Node, while babel-loader is for Webpack).  Babel [recommend](https://babeljs.io/env/) the use of babel-preset-env over babel-preset-es2015 if possible.

Glad we were both able to find workarounds, though this module should just sort of work regardless.

**Comment by TimvanScherpenzeel** [comment]
I agree, I use `babel-preset-env` where possible. I opened a ticket myself about it a while ago but it seems that 13 hours ago the changes got merged in a different ticket 👍

https://github.com/toji/gl-matrix/pull/268

**Comment by bes** [comment]
I just ran into this issue for Safari 9.

I did some investigating, and changing gl-matrix/package.json to include

```
"browser": "./dist/gl-matrix-min.js",
```

seemed to fix this issue (Webpack 4).

**Comment by stefnotch** [comment]
https://github.com/toji/gl-matrix/pull/335 should address this issue. If not, I'll reopen it.
