### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by stefnotch** [toji/gl-matrix#291]
@toji I merged a bunch of PRs and bumped up the gl-matrix version. 

Would you mind running `npm publish`?

Also, I have a question: Should I merge the `quat2` PR? (After making sure that everything works.) It should be fairly isolated from the rest of the code, so, the risk of breaking anything is very low.

**Comment by maierfelix** [comment]
npm ownerships can be transfered, [link](https://docs.npmjs.com/cli/owner)

**Comment by stefnotch** [comment]
And, solved.
