### ISSUE TITLE
Future tasks

### ISSUE THREAD

**Issue by stefnotch** [toji/gl-matrix#295]
- [ ] WebAssembly port
- [ ] Better tutorials

**Comment by maierfelix** [comment]
The Webassembly port can possibly get automated - I did some experiments and by parsing each module's comments and receiving the type information from there. Only a few methods of each module would have to be ported manually

**Comment by stefnotch** [comment]
@maierfelix That's amazing! 😃

**Comment by maierfelix** [comment]
Thanks!
The benchmarks are not completely reliable though, it's tricky to benchmark against v8. I'd be thankful if someone could investigate into this to see if the port is useful at all.

**Comment by stefnotch** [comment]
![capture](https://user-images.githubusercontent.com/10220080/39351172-fa10bf9c-4a00-11e8-92ce-eab48cddfe59.JPG)

I tested the benchmarks with Firefox and Chrome. (Also, as you can see, both browsers limited the resolution of the timers because of Meltdown and Spectre) Either the benchmarks aren't that reliable or Firefox is better at optimizing this sort of code. You could try using [benchmark.js](https://benchmarkjs.com/) and see if the results of the benchmarks change.

**Comment by stefnotch** [comment]
@maierfelix 

> The Webassembly port can possibly get automated - I did some experiments and by parsing each module's comments and receiving the type information from there

Mind elaborating? That seems pretty interesting. 😃

**Comment by stefnotch** [comment]
Re-ran the benchmarks on Firefox, it's now consistently faster.

**Comment by stefnotch** [comment]
(Housekeeping) Duplicate of https://github.com/toji/gl-matrix/issues/283
