### ISSUE TITLE
Add `alloc` methods

### ISSUE THREAD

**Issue by d07RiV** [toji/gl-matrix#301]
In many cases we need to just allocate space for a vector/matrix/etc, and it doesn't make sense to waste time filling them in with any default values. We can use `new Float32Array(3)`, or even `new glMatrix.ARRAY_TYPE(3)`, but wouldn't it be a lot better if the types exposed a method for allocating space, so we could write `vec3.alloc()` instead?

**Comment by stefnotch** [comment]
A benchmark would be nice.

**Comment by stefnotch** [comment]
After running a bunch of quick benchmarks, it would appear that this definitely makes sense. 

Currently, my only concern is that `new Float32Array(NUMBER)` and `new Array(NUMBER)` have different default values. A `Float32Array` is filled with 0s while a normal `Array` is filled with undefined.

**Comment by d07RiV** [comment]
That's true, but the idea is to create an uninitialized object that has to be filled in before use.

**Comment by stefnotch** [comment]
@d07RiV Well, I'm fearing that there would be a bunch of people relying on `.alloc` filling everything with 0s and then, their code breaks whenever Float32Array isn't supported.

**Comment by d07RiV** [comment]
What about having the array version fill everything with 0 through some sort of check? I don't think that small performance loss will be a big deal compared to using arrays in the first place.

**Comment by stefnotch** [comment]
@d07RiV That's a great idea! 😄 I'm going to implement it sometime within the next few weeks. However, if you want to, you can also create a PR.
