### ISSUE TITLE
package.json has broken "main" field

### ISSUE THREAD

**Issue by Fuzzyma** [toji/gl-matrix#310]
When you `npm install` the package as is and use `require('gl-matrix')`, this library will not work in nodejs anymore because at some point the `main` field in the package.json was changed to `dist/gl-matrix` where it should be `src/gl-matrix`.
You dont want to use the webpacked version when you use node.
Please correct this because otherwise nobody can use this package anymore

**Comment by stefnotch** [comment]
(Relevant issue: https://github.com/toji/gl-matrix/issues/277 )

@andrevenancio You probably know more about this than I do.

**Comment by andrevenancio** [comment]
Hi @Fuzzyma, you are right, the `main` property in the `package.json` points to the "compiled" version. I don't know why `module` was added. It was introduced by @toji with this [commit](https://github.com/toji/gl-matrix/commit/7850f1f1e09be244f3bf84aa7208e45259b4d9b1)

From what I can ascertain the `module` property is meant to be used by webpack and rollup as ES6 modules (allowing three shaking).

With that said, I just want to point out that the exported version on the `dist/` folder (`dist/gl-matrix.js`) though it has some comments introduced by webpack, its not a `webpack` version. Webpack is exporting with the UMD option which exposes the library under all the module definitions, allowing it to work with CommonJS, AMD and as global variable.

We can remove the comments from that version (and we should @stefnotch ) but still the only thing that's happening is that you're merging all the files into one.

Unless I'm missing something this should not be a problem.

**Comment by andrevenancio** [comment]
@Fuzzyma  Can you pull my version https://github.com/toji/gl-matrix/pull/312 and give it a go on your node app?

I've tested this locally with something very simple, and it seems to work

test.js
```
var vec3 = require('gl-matrix').vec3;
console.log(vec3.create());
```

and running
```
node test.js
```

returns the expected `Float32Array [ 0, 0, 0 ]`

Give it a go too @stefnotch

**Comment by Fuzzyma** [comment]
the `windows` was were my code was breakig. However this was just reported to my repo. I cannot test it atm but I am pretty sure it should work now. I will report back when my people close the issue on my repo
