### ISSUE TITLE
Optimization : vec3.transformQuat

### ISSUE THREAD

**Issue by SpaceIm** [toji/gl-matrix#317]
Hello,
here is a slighly faster implementation of vec3.transformQuat :
https://jsperf.com/quaternion-transform-vec-optimization
```
export function transformQuat(out, a, q) {
    const qx = q[0];
    const qy = q[1];
    const qz = q[2];
    const qw = q[3];
    const x = a[0];
    const y = a[1];
    const z = a[2];

    const uvx = 2 * (qy * z - qz * y);
    const uvy = 2 * (qz * x - qx * z);
    const uvz = 2 * (qx * y - qy * x);

    out[0] = x + qw * uvx + qy * uvz - qz * uvy;
    out[1] = y + qw * uvy + qz * uvx - qx * uvz;
    out[2] = z + qw * uvz + qx * uvy - qy * uvx;
    return out;
}
```

**Comment by stefnotch** [comment]
Awesome! Do you want to create a PR or should I take care of it?

**Comment by stefnotch** [comment]
Awesome!

Though, after benchmarking a bit more, it appears that the changes incur a 10% performance penalty when using Firefox.

**Comment by SpaceIm** [comment]
Urgh, yes, you're right, after more benchmark using Firefox 60 with windows7 and windows10 :
Windows 7 : 6% faster
Windows 10 : 10-11% slower...

With others web browsers, it depends, but you're current implementation seems to be faster in average. Sorry.

**Comment by stefnotch** [comment]
@SpaceIm Too bad that it's slower in Firefox. So, I'm closing this issue for now.

Though, JavaScript engines keep changing. At some point, your implementation might be faster in Firefox as well.
