### ISSUE TITLE
dist should be compiled in production mode

### ISSUE THREAD

**Issue by gera2ld** [toji/gl-matrix#319]
Currently `dist/gl-matrix.js` is compiled in `development` mode. All code is wrapped in `eval(...)`, which is supposed to be used for debugging.

As a result, if the compiler resolves the module by `main` field of `package.json` (e.g. rollup, webpack<=3),  the development code which should not be used in production mode will be bundled.

I think all code in `dist` directory should be compiled in `production` mode, and `gl-matrix.min.js` is a minified version of `gl-matrix.js`.

**Comment by stefnotch** [comment]
Relevant line:
https://github.com/toji/gl-matrix/blob/fa7614cc19ba7edd9cd80c1bb68a8ffe68320a58/utils/webpack.config.js#L23

**Comment by gera2ld** [comment]
Another consideration about the compilation:

Can we add `output.library = 'glMatrix'` to webpack config so that all exports will be attached to a global variable `glMatrix`, instead of polluting the `window` object with a lot of short-named variables (vec4, vec3, etc.).

**Comment by stefnotch** [comment]
@gera2ld Please open a new issue for that.
