### ISSUE TITLE
mat4.perspective problem?

### ISSUE THREAD

**Issue by lmj01** [toji/gl-matrix#324]
version 1.3.7 work well, but version 2.6.1 not work well,
someone get problem ?

**Comment by stefnotch** [comment]
@lmj01 Passing Math.Infinity or null to the last parameter now properly creates an infinity-perspective matrix: https://github.com/toji/gl-matrix/pull/318

**Comment by lmj01** [comment]
I wrap gl-matrix for my code, i commit the mat4.perspective, it work fine, but i set the prespective , the result is not in scene viewport, may it will change in shader multiply order

**Comment by stefnotch** [comment]
@lmj01 Sorry, this is a bit hard to understand. 

So, you've already pinned down the issue to mat4.perspective? If  you use the

**Comment by lmj01** [comment]
@stefnotch , sorry,  i don't gei much more information about the problem.
I test for single method, it get the result, 
my scenario is , when I set mat4.targetTo, and multiply the perspective project, the result is very unpredicate. in old version, i don't have the problem, so i got the confused by this, 
and because i comment the the mat4.perspective, it work well,  
[call this function, all the parameter are the same]

**Comment by stefnotch** [comment]
1) If you use the code I posted above [mat4.perspective](https://github.com/toji/gl-matrix/issues/324#issuecomment-402952027) does it work?

2) Which old version are you exactly referring to? 1.3.7? If yes, please take a look at https://github.com/toji/gl-matrix/issues/142

**Comment by lmj01** [comment]
code is very common, i got the problem, the #142 give me to cause
