### ISSUE TITLE
How to make camera lookAt?

### ISSUE THREAD

**Issue by dakom** [toji/gl-matrix#325]
I'm trying to understand how to use `lookAt` or `targetTo` to make the `view` matrix for a camera.

Playing around with some test vectors leaves me confused... help is appreciated!

What should I use if I want to have a camera positioned at [2,0,-7] and have it look at the center of the world at [0,0,0] ?

In other words that view will be used to construct the modelViewMatrix which gets multiplied with all the vertices in the shader

Here's some tests which led to my confusion... thanks!

```
const {mat4, quat, vec3} = require('gl-matrix');

const makeVector = (eye, style) => {
  const center = [0,0,0];
  const up = [0,1,0];

  const lookMatrix = style === "look"
    ? mat4.lookAt(mat4.create(), eye, center, up)
    : mat4.targetTo(mat4.create(), eye, center, up);

  return vec3.transformMat4(vec3.create(), [0,0,0], lookMatrix); 
}

//these are the same
makeVector([0,0,-7], "look"); //=> Float32Array [ 0, 0, -7 ]
makeVector([0,0,-7], "target"); //=> Float32Array [ 0, 0, -7 ]

//but these are different?
makeVector([0,0,7], "look"); //=> Float32Array [ 0, 0, -7 ]
makeVector([0,0,7], "target"); //=> Float32Array [ 0, 0, 7 ]

//these are different too...
makeVector([2,0,-7], "look"); //=> Float32Array [ 0, 0, -7.280109882354736 ]
makeVector([2,0,-7], "target"); //=> Float32Array [ 2, 0, -7 ]
```

**Comment by stefnotch** [comment]
Here is some information regarding that: https://github.com/toji/gl-matrix/issues/225

You probably want to use `targetTo`.
