### ISSUE TITLE
Specify sideEffects: false in package.json

### ISSUE THREAD

**Issue by davazp** [toji/gl-matrix#326]
For webpack to take benefit of tree-shaking, the library must be declared as `"sideEffects": false` in the `package.json`, as described in https://webpack.js.org/guides/tree-shaking/#conclusion

Without this, the library users are forced to override this within the webpack rules with
```javascript
{
  include: path.resolve("node_modules", "gl-matrix"),
  sideEffects: false
}
```

**Comment by stefnotch** [comment]
Feel free to create a PR. I would appreciate it. 😄
