### ISSUE TITLE
Maybe another `mat4.getRotation` -like method, works with `mat4. fromRotationTranslationScale`

### ISSUE THREAD

**Issue by xieguanglei** [toji/gl-matrix#332]
Thanks for the great library!

As the document says, if a matrix is built with `mat4.fromRotationTranslation`, the returned quaternion of `mat4.getRotation` will be the same as the quaternion originally supplied.

But I'm using `mat4.fromRotationTranslationScale` to create the matrix, I've got no quick way to reverse back the translation, rotation originally supplied. Any suggestions?

**Comment by stefnotch** [comment]
Doesn't `mat4.getRotation` work with arbitrary matrices?

**Comment by xieguanglei** [comment]
Simplified sample code is here:

https://jsbin.com/sotutuy/edit?js,console

Thanks!

**Comment by stefnotch** [comment]
Thank you for providing a sample of the issue.

So, gl-matrix uses the following code:
http://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToQuaternion/index.htm

Relevant quotes (bold styling added by me):

> ### Issues
> (1) This page assumes that the input matrix represents a pure rotation otherwise the resulting quaternion will not be valid. This implies that **the matrix must be special orthogonal**, that is both:
>   * the matrix is orthogonal
>   * In addition the matrix is special orthogonal (pure rotation without reflection component)


> ### Scaling
> Since it is possible for both matrices and quaternions to represent scaling in addition to rotation, then it would be possible to include this in the convertion. [..]
> **Of course, this will mean that the matrix is no longer orthogonal and that the quaternion is no longer normalised.**

**Comment by xieguanglei** [comment]
I'm not fully understand …… , is it by design because of a mathematics issue ? or is a bug which can be fixed sometime later?

**Comment by stefnotch** [comment]
It's a [bug](https://github.com/toji/gl-matrix/issues/332#event-1734239504) which can be fixed. However, fixing it probably comes with a performance penalty.

**Comment by stefnotch** [comment]
Due to the performance penalty, this bug will probably not get fixed anytime soon.

**Comment by IcanDivideBy0** [comment]
@xieguanglei and anyone else wondering what's going on with their rotations, take a look at this version for a quick fix https://github.com/toji/gl-matrix/issues/245

**Comment by stefnotch** [comment]
Fixed in https://github.com/toji/gl-matrix/pull/353
