### ISSUE TITLE
NPM published package.json not consistent with this repo

### ISSUE THREAD

**Issue by renchap** [toji/gl-matrix#333]
Here is the `package.json` file for 2.7.0 when installing from NPM: https://unpkg.com/gl-matrix@2.7.0/package.json

It still contains 
```
  "dependencies": {
    "npm": "^6.2.0"
  },
```

The `package.json` file in this repo tagged with 2.7.0 does not contain this: https://github.com/toji/gl-matrix/blob/v2.7.0/package.json

I guess something wrong happened when pushing the version 2.7.0 to NPM.

Could you please release a 2.7.1 with the correct `package.json`? Thanks!

**Comment by stefnotch** [comment]
Oh, sorry for that. Fixed it and published a new version.

Apparently it was caused by updating npm using `npm i npm`.
