### ISSUE TITLE
I use gl-matrix version 2.3.8 build is normal, when I use the version above 2.4.0 SyntaxError

### ISSUE THREAD

**Issue by coldice945** [toji/gl-matrix#338]
I have a project use dependencies gl-matrix.
When I build use browserify, I find it error.

> events.js:183
      throw er; // Unhandled 'error' event
      ^
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

I find when I use  gl-matrix version 2.3.8, It become normal. When I use the above 2.4.0,It become SyntaxError.
Do you know why?

**Comment by stefnotch** [comment]
A minimal test case to reproduce this would be great. Would it be possible for you to send me a test project with that error, or explain how to set up such a test project?

**Comment by stefnotch** [comment]
@coldice945 Would you mind trying out [v3.0.0](https://www.npmjs.com/package/gl-matrix/v/3.0.0).

**Comment by coldice945** [comment]
It's worked

**Comment by stefnotch** [comment]
Thank you very much for your prompt response.
