### ISSUE TITLE
Non-minified script is still minified

### ISSUE THREAD

**Issue by AshleyScirra** [toji/gl-matrix#340]
In dist/, gl-matrix.js is the same as gl-matrix-min.js. That file should not be minified.

**Comment by stefnotch** [comment]
Changing 
https://github.com/toji/gl-matrix/blob/6866ae93d19bbff032139941cbfe0ae68c4cdead/utils/webpack.config.js#L23 

to `mode: 'none'` seems to "fix" it.

**Comment by stefnotch** [comment]
Fixed! Shout-out and thanks to TrySound!

**Comment by AshleyScirra** [comment]
Can you publish an updated release with the correct unminified script? I can't run build myself, it fails with `TypeError: Cannot read property 'properties' of undefined`.

**Comment by AshleyScirra** [comment]
Is that backwards-compatible with 2.8.1? I assumed it wasn't, based on the major version bump.
