### ISSUE TITLE
Publish the relase version of v3.0.0 

### ISSUE THREAD

**Issue by stefnotch** [toji/gl-matrix#347]
Currently, it's just a pre-release.
https://github.com/toji/gl-matrix/releases/tag/v3.0.0-0

https://www.npmjs.com/package/gl-matrix?activeTab=versions

**Comment by stefnotch** [comment]
The main thing that has changed is:
https://github.com/toji/gl-matrix/pull/339
https://github.com/toji/gl-matrix/pull/343
https://github.com/toji/gl-matrix/pull/345

**Comment by stefnotch** [comment]
https://www.npmjs.com/package/gl-matrix?activeTab=versions

**Comment by TrySound** [comment]
Yay!
