### ISSUE TITLE
Clarification of `gl-vec3. transformMat4`

### ISSUE THREAD

**Issue by nkint** [toji/gl-matrix#348]
Hi!
I am new to math so sorry for my ignorance, but I just like to understand things.
More then an issue caused by a bug this is a need of clarification, sorry again if this is not the right place.

I'm porting some geometry old code from [processing.org](https://processing.org/) java framework to javascript with `gl-matrix`. For instance I used [toxiclibs](https://github.com/shiffman/toxiclibs).

In that code I'm encoding some quaternion rotations into a matrix and then I need to transform all point of a mesh within that matrix.

I'm stucked on what in `toxiclibs` is called `TriangleMesh.transform(Matrix4x4)` (see [here](https://github.com/shiffman/toxiclibs/blob/master/src.core/toxi/geom/mesh/TriangleMesh.java#L912)):
>  Applies the given matrix transform to all mesh vertices. [...]

This method itself calls `Vec3D Matrix.applyTo(Vec3D v)` (see [here](https://github.com/shiffman/toxiclibs/blob/master/src.core/toxi/geom/Matrix4x4.java#L314)) that, as the name says, transform a Vec3 by a Matrix4x4.

I need to _translate_ this in `gl-matrix` and I thought I need to use `gl-vec3.transformMat4` (see [here](https://github.com/toji/gl-matrix/blob/master/src/vec3.js#L479)):
> Transforms the vec3 with a mat4. 4th vector component is implicitly '1'

But results are totally difference and I ended up rewriting the `transform` method from the toxiclibs in that way to have the result I'm expecting:

```ts
/**
 * Applies the given matrix 4x4 `matrix` transform to the input vec3 `v`.
 * @param {vec3} out the receiving vector
 * @param {vec3} v the vector to transform
 * @param {mat4} m matrix to transform with
 * @returns {vec3} out
*/
function transform(out: Vec3, v: Vec3, matrix: Mat4): Vec3 {
  const temp: Mat3 = mat3.create()
  const width: number = 4
  for (let i = 0; i < width; i++) {
    temp[i] =
      v[0] * matrix[0 + i * width] +
      v[1] * matrix[1 + i * width] +
      v[2] * matrix[2 + i * width] +
      matrix[3 + i * width]
  }
  out[0] = (temp[0] * 1.0) / temp[3]
  out[1] = (temp[1] * 1.0) / temp[3]
  out[2] = (temp[2] * 1.0) / temp[3]
  return out
}
```

Note that this method has the same signature of `gl-vec3.transformMat4`

So.. I don't really understand the math behind (and would really thank someone if can explain to me) but basically.. what I'm doing wrong? Which `gl-matrix` method do I need?

**Comment by stefnotch** [comment]
### Reproduction code
Setup
```javascript
function transform(out, v, matrix) {
  const temp = mat3.create()
  const width = 4
  for (let i = 0; i < width; i++) {
    temp[i] =
      v[0] * matrix[0 + i * width] +
      v[1] * matrix[1 + i * width] +
      v[2] * matrix[2 + i * width] +
      matrix[3 + i * width]
  }
  out[0] = (temp[0] * 1.0) / temp[3]
  out[1] = (temp[1] * 1.0) / temp[3]
  out[2] = (temp[2] * 1.0) / temp[3]
  return out
}

a = [1,3,5]

let q = quat.create();
let t = vec3.fromValues(1, 2, 3);
let s = vec3.fromValues(5, 6, 7);
q = quat.setAxisAngle(q, [0, 1, 0], 0.7);
let b = mat4.create();
mat4.fromRotationTranslationScale(b, q, t, s);

out = [0,0,0]
```
Test
```javascript
transform(out, a, b)
// [ -0.5339665620223336, 0.782608695652174, 1.3599564925484036 ]

vec3.transformMat4(out, a, b)
// [ 27.371830224990845, 20, 26.54838752746582 ]
```

Second test (transpose matrix)
```javascript
transposed = mat4.create()
mat4.transpose(transposed, b)
transform(out, a, transposed)
// [ 27.371829986572266, 20, 26.54838752746582 ]

vec3.transformMat4(out, a, b)
// [ 27.371830224990845, 20, 26.54838752746582 ]
```
