### ISSUE TITLE
mat4.makeTranslate/Rotate/Scale

### ISSUE THREAD

**Issue by toji** [toji/gl-matrix#35]
A coworker suggested that it may be nice to have functions in place that create or set translation, rotation, or scale matrices. I feel like that would be a great idea that could potentially make the library more comfortable to work with for people coming from certain environments.

The basic usage of each function would be:

``` javascript
mat4.makeTranslate([x, y, z], dest);
```

Which would be functionally identical to:

``` javascript
mat4.identity(dest);
mat4.translate(dest, [x, y, z], dest);
```

But would allow us to skip some math since we're not worried about the previous matrix state. As with `identity` if no `dest` is provided we would create a new mat4 and return it. Obviously there's a use case for having similar methods for `mat3` as well. I'm not sure about `mat2`.

I'm not 100% sold on the name, as I could see it being either `make___`, `create___`, or `set___`. I'm all ears on opinions there. Also, in keeping with the pattern set by the `create` functions we may want to consider having variants that take vectors and variants that take individual components.

**Comment by stefnotch** [comment]
glmatrix supports those functions, so, I can close this issue.

e.g. glmatrix.net/docs/module-mat4.html#.fromTranslation
