### ISSUE TITLE
can I import gl-matrix without webpack?

### ISSUE THREAD

**Issue by jack-shanghai** [toji/gl-matrix#354]
I want to use gl-matrix with import grammar, so I use it like this
`<script src="./index.js" type="module"></script>`  
`import mat4 from '../utils/src/mat4.js'`
unfortunately, the chrome dev tool print

> Uncaught SyntaxError: The requested module '../utils/src/mat4.js' does not provide an export named 'default'

if I use like this `import {create} from '../utils/src/mat4.js'`, it would work. Howerver, I need to update it while I need use a new function

**Comment by stefnotch** [comment]
Yes, you very much can. 

Your issue stems from the fact that `mat4.js` does not have a default export, but rather has a number of named imports for each function. If you want to import all of them at once, you can use
```
import * as mat4 from '../utils/src/mat4.js', 
```
[This is exactly what index.js does](https://github.com/toji/gl-matrix/blob/master/src/index.js).


Now, if you want to import `mat4` from `index.js`, you have to include curly brackets around it `{ }`.
```
import { mat4 } from '../utils/src/index.js';

import { mat4, vec3, quat2} from '../utils/src/index.js'; // You can also import multiple things at once.
```

**Comment by jack-shanghai** [comment]
thank you very much, how foolish I am!

**Comment by stefnotch** [comment]
Glad I could help you.
