### ISSUE TITLE
ES6 module import from a browser

### ISSUE THREAD

**Issue by legends2k** [toji/gl-matrix#371]
I've just `dist/gl-matrix.js` checked in to my repository.  There're HTML5 documents that do

```html
<head>
  <script type="text/javascript" src="../gl-matrix.js"></script>
  <script type="text/javascript" src="../my_utils.js"></script>
</head>

<body>
  <script>
    const {vec2, vec4} = glMatrix;  // needed since gl-matrix 3.0.0
  </script>
</body>
```

I understand that this needs `const {vec4} = glMatrix;` to use `vec4` without `glMatrix.`. However, I use `vec2`, etc. in `my_utils.js` as well, and if I do `const {vec4} = glMatrix;` there I get a redeclaration error.

To counter this, I thought I'll go the ES6 module import route.  Doing

```html
<script type="module">
import {vec2} from '../gl-matrix.js';
</script>
```

gives me

> SyntaxError: import not found: vec2

Likewise, in `my_utils.js` doing

```js
import {vec4} from "./gl-matrix.js"
```
gives me

> SyntaxError: import not found: vec4

What am I doing wrong?  Or does `gl-matrix.js` not export anything?  When I run the debugger, I only see `glMatrix` object where `vec2`, `vec4`, etc. are members.

**I don't want to use `index.js` as it means checking in a bunch of gl-matrix files when I need only a single JS.**

**Comment by TrySound** [comment]
gl-matrix.js is not esm compatible
Here's what you should import
https://unpkg.com/browse/gl-matrix@3.1.0/esm/index.js

**Comment by legends2k** [comment]
@TrySound But wouldn't that mean also needing common.js, mat2.js, mat2d.js, mat3.js, mat4.js, quat.js, quat2.js, vec2.js, vec3.js, vec4.js files too?  Is there no way to get away with just one file?

**Comment by TrySound** [comment]
You can use pika to get single esm bundle.
https://www.pika.dev/npm/gl-matrix

**Comment by legends2k** [comment]
Wow, this works well. Thanks!

**Comment by 8Observer8** [comment]
If you want a custom version you can use @ like:

```
import { vec3, mat4 } from "https://cdn.skypack.dev/gl-matrix@3.4.3";
```

Useful example:
```
<body>
    <script async src="https://unpkg.com/es-module-shims@1.3.6/dist/es-module-shims.js"></script>

    <script type="importmap">
        {
            "imports": {
                "gl-matrix": "https://cdn.skypack.dev/gl-matrix@3.4.3"
            }
        }
    </script>

    <script type="module">
        import { vec3 } from "gl-matrix";

        const vec = vec3.create();
        console.log(vec);
    </script>

</body>
```
