### ISSUE TITLE
Consider removing docs from npm

### ISSUE THREAD

**Issue by vorg** [toji/gl-matrix#372]
Out of 2.6MB of this module the docs take 1.9MB. How often people use docs from node_modules folder? A compromise would be switching to google fonts link as OpenSans itself takes 1MB.

**Comment by stefnotch** [comment]
Which version did you install? I cannot reproduce this with the latest version.

**Comment by TrySound** [comment]
@vorg No problem in latest version
https://packagephobia.now.sh/result?p=gl-matrix@3.1.0

**Comment by vorg** [comment]
True true. It's on of my deps using it so i guess i have to bug them. Thanks!
