### ISSUE TITLE
how to import vec2 to my proyect client side?

### ISSUE THREAD

**Issue by jebito** [toji/gl-matrix#373]
I'm trying to import just vec2 on my client side but i can't get it to work I tried this.

import * as vec2 from "./vec2.js"; 

and return this error:
 SyntaxError: import declarations may only appear at top level of a module

**Comment by stefnotch** [comment]
How are you including gl-matrix into your project?

By the way, if you search for the error message, you'll find a number of relevant results on Google such as [this StackOverflow Question related to JavaScript modules](https://stackoverflow.com/questions/37624819/es2015-import-doesnt-work-even-at-top-level-in-firefox).

**Comment by jebito** [comment]
<!DOCTYPE` html>
<head>   
</head>
<body>
    <script src="/socket.io/socket.io.js"></script>
    <script src="js/gl-matrix-min.js" type="module"></script>
    
    <script> let socket = io(); </script>
    <script src="js/phaser.js"></script>
    <script src="js/body.js"></script>

    <script src="js/game.js"></script> 
</body>
</html>

**Comment by jebito** [comment]
sorry I'm new on this i closed it by mistake ok what I did was this.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
</head>
<body>
    <script src="js/body.js"></script>
</body>
</html>
```
inside body.js:
`import * as vec2 from "./vec2.js"; `

so that way i can create:`var vector = vec2.create();`

and inside vec2.js for default there is:
`import * as glMatrix from "./common.js";`

I was following https://github.com/toji/gl-matrix/issues/354

**Comment by stefnotch** [comment]
You have to tell the browsers that you want to use Javascript modules, like in #354
> `<script src="./index.js" type="module"></script>`
