### ISSUE TITLE
Typescript: mat4 returns type instead of module

### ISSUE THREAD

**Issue by evertmonk** [toji/gl-matrix#380]
Version: 3.2.1

When doing `import { mat4 } from 'gl-matrix'` and then compiling from typescript to javascript throws following error: 
```
 TS2339: Property 'set' does not exist on type 'mat4'.
  Property 'set' does not exist on type '[number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number]'.
```

It seems that typescript imports the `type mat4` and not the `module mat4`.
It is also probably happening on the other functions, but have not checked those.

**Comment by stefnotch** [comment]
That's odd. Could you post a reproduction project?

**Comment by evertmonk** [comment]
I have created a small setup that can reproduce this issue here: [https://github.com/evertmonk/gl-matrix-typescript-reproduction](https://github.com/evertmonk/gl-matrix-typescript-reproduction)

**Comment by stefnotch** [comment]
```
import { mat4 } from 'gl-matrix';

const test: mat4 = mat4.create();
test.set([
  1, 1, 1, 1,
  1, 1, 1, 1,
  1, 1, 1, 1,
  1, 1, 1, 1
]);
```
That's sadly not quite how `gl-matrix` works. `gl-matrix` directly operates on arrays or Float32Arrays and thus has a different syntax.
You want
```
const test: mat4 = mat4.create();
mat4.set(test, 
  1, 1, 1, 1,
  1, 1, 1, 1,
  1, 1, 1, 1,
  1, 1, 1, 1
);
```

**Comment by evertmonk** [comment]
Thanks for clearing that up. I will change accordingly.

**Comment by magcius** [comment]
This is an breaking change from the old JSDoc types. Previously, it was allowed.
