### ISSUE TITLE
Proposal: Relax type to arrays in types.d.ts 

### ISSUE THREAD

**Issue by anvaka** [toji/gl-matrix#386]
Hello,

I was curious if community would be open to relax type strictness in the [types.d.ts](https://github.com/toji/gl-matrix/blob/master/src/types.d.ts) file. 

Instead of 

``` ts
declare type vec2 = [number, number] | Float32Array;
```

I propose to use

``` ts
interface IndexedCollection {
    readonly length: number;
    [n: number]: number;
}
declare type vec2 = [number, number] | IndexedCollection;
```

Main motivation behind this is that it is possible to to change matrix type to be, say `Float64Array` or anything else that looks like an array via `setMatrixArrayType()`, and current type definitions do not reflect this accurately.

If you are open to this suggestion I'd be happy to send a pull request.

**Comment by stefnotch** [comment]
I'm all for it. After all, WebGL also accepts other typed arrays. So, yes, please do open a PR.
