### ISSUE TITLE
How to set length of a vector?

### ISSUE THREAD

**Issue by kevzettler** [toji/gl-matrix#388]
Hello i'm porting some C++ code that has a `Vector.SetLength` method

```
VECTOR V = vel;
V.SetLength(collisionPackage->nearestDistanceveryCloseDistance);
```

How would I reproduce that with `gl-matrix` not seeing it as a `vector` method?

**Comment by stefnotch** [comment]
gl-matrix doesn't have setter methods for most things, instead it has methods that modify the current values. So, you first have to [get the current length](http://glmatrix.net/docs/module-vec3.html#.length) or have a [normalized vector](http://glmatrix.net/docs/module-vec3.html#.normalize) and then modify it accordingly with the [`scale` function](http://glmatrix.net/docs/module-vec3.html#.scale).

**Comment by kevzettler** [comment]
Hi @stefnotch thanks for your response can you help me understand a bit more. I'm not sharp on the math. Is it fair to say these code examples are equivalent? 

```
VECTOR V = vel;
V.SetLength(collisionPackage->nearestDistancevery - CloseDistance);
```

```
const V = vec3.create();
vec3.scale(
V,
collisionPackage.nearestDistancevery - CloseDistance
)
```

**Comment by stefnotch** [comment]
Not quite, in the first one you're setting the vector `V = vel;`. 
In the ported version, you're creating a new vector with the values (0,0,0). Also note that pretty much every gl-matrix function has an out parameter. Aka, the vector where the values will be written to.

If the velocity has a length of one, this would be correct.
```javascript
const V = vec3.clone(vel);
vec3.scale(V, V, collisionPackage.nearestDistancevery - CloseDistance);
```
If you're not sure, this is safer.

```javascript
const V = vec3.clone(vel);
vec3.scale(V, V, (collisionPackage.nearestDistancevery - CloseDistance) / vec3.length(V));
```

**Comment by kevzettler** [comment]
thanks @stefnotch !
