### ISSUE TITLE
Drop IE support

### ISSUE THREAD

**Issue by stefnotch** [toji/gl-matrix#395]
It might be worthwhile to drop support for ancient browsers such as IE 11 at some point. Then we wouldn't have to transpile code to such an old Javascript version. Also, the usage of `Math.hypot` wouldn't cause any issues anymore.

**Comment by toji** [comment]
I'm in favor of it!

**Comment by mreinstein** [comment]
I think it's time, especially if we're going to bump semver major on gl-matrix anyway.

**Comment by toji** [comment]
As mentioned in #453, IE support will no longer be a consideration for v4 and higher.
