### ISSUE TITLE
vec3.direction returns reverse direction

### ISSUE THREAD

**Issue by OleLaursen** [toji/gl-matrix#45]
vec3.direction([0, 0, 0], [0, 0, 1]) returns [0, 0, -1] rather than [0, 0, 1] as expected and as the documentation says it should. I'm on an old release but I checked the latest source and it certainly appears to have the same bug.

**Comment by stefnotch** [comment]
@toji @sinisterchipmunk This issue can be closed because the function (`vec3.direction`) doesn't exist anymore.
