### ISSUE TITLE
mat3.fromQuat unit test

### ISSUE THREAD

**Issue by pastasfuture** [toji/gl-matrix#95]
Noticed results from quat.rotationTo(out, a, b) conflict with expected results in the mat3.fromQuat unit test.

quat.rotationTo(out, [0,0,-1], [-1,0,0]) returns quat [0, 0.7071067690849304, 0, 0.7071067690849304]  

while the mat3.fromQuat unit test expects quat [ 0, -0.7071067811865475, 0, 0.7071067811865475 ] to rotate [0,0,-1] to [-1,0,0]
https://github.com/toji/gl-matrix/blob/master/spec/gl-matrix/mat3-spec.js#L87

**Comment by stefnotch** [comment]
@toji @sinisterchipmunk @pastasfuture This issue can be closed.
